Repository gjohansson-ST/attribute_as_sensor, pull requests merged in 2024-11, with the labels that each got.

#18 Create pt.json
  custom_components/attribute_as_sensor/translations/pt.json
Labels: enhancement

#19 Move platform constant to const.py
  custom_components/attribute_as_sensor/__init__.py
  custom_components/attribute_as_sensor/const.py
Labels: refactor

#20 Update also on report events
  custom_components/attribute_as_sensor/sensor.py
Labels: enhancement

#21 Error when attribute is missing from source sensor
  custom_components/attribute_as_sensor/__init__.py
  custom_components/attribute_as_sensor/sensor.py
Labels: enhancement

#22 New version
  README.md
  custom_components/attribute_as_sensor/manifest.json
Labels: enhancement

#23 Fix readme
  README.md
Labels: documentation
